Added share button on page component
nathgoutam93/linkpile-react pull request #10
Opened 2022-02-19 21:48 UTC by A-BMT02

Main Changes :
1. Added Share button on Page Component .
2. Custom CSS styling for the button at index.css

2022-02-20 09:28 UTC, nathgoutam93 requested changes

2022-02-20 09:28 UTC, nathgoutam93 commented on src/pages/page.js
> +  const { username } = state;
useAdmin hook will return the information of who is logged in , but in this case we do not need the username of the logged in person instead the username of the person we are currently visiting the page of. and that can be done by looking the userId parameter of the url . which is already done by userParams ,

2022-02-20 09:28 UTC, nathgoutam93 commented on src/pages/page.js
> +    navigator.clipboard.writeText(`https://linkpile-bffd7.web.app/${username}`);
change this username with userId that we are getting from the useParams()

2022-02-20 09:28 UTC, nathgoutam93 commented on src/pages/page.js
> +    console.log(`https://linkpile-bffd7.web.app/${username}`) ;
remove this console log

2022-02-20 09:28 UTC, nathgoutam93 commented on src/pages/page.js
> +import { ShareAdmin } from "../components/share";
share admin and BsAlignButton not in use remove those from import

2022-02-21 23:00 UTC, A-BMT02 commented
I merged our repositories and pulled. 
Seems like you took out all the code related to the share button

2022-02-22 09:04 UTC, merged